### ISSUE TITLE
thing doesn't work rihjt

### ISSUE THREAD

**Issue by chaitunya** [Shubham-SK/TreeOverAte#1]
pls help me i don't know why its not working

i asked someone an they told me to pres alt f4 but it didn work.

**Comment by Shubham-SK** [comment]
**bruh**

**Comment by Shubham-SK** [comment]
Try againe.

**Comment by chaitunya** [comment]
uhh i tried it againe but it didn work rihjt

**Comment by chaitunya** [comment]
it works right now rihjt

**Comment by psrisank** [comment]
I dont think it will work for you anymore

**Comment by Shubham-SK** [comment]
stop reopening the issue smfh

**Comment by psrisank** [comment]
Its still a problem man.
